config/routes.rb
Rails.application.routes.draw do
  get 'sacas/:fecha/:persona_id', to: 'sacas#new', as: 'new_saca'
  root 'sacas#index'
  resources :sacas
  resources :personas
  resources :alumnos
  resources :salidas

end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
  belongs_to :salida
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno was successfully created.' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Alumno was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Alumno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:rut, :nombre, :salida_id)
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/views/alumnos/_form.html.erb
<%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% @alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rut %><br>
    <%= f.text_field :rut %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :salida_id %><br>
    <%= f.text_field :salida_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alumnos/edit.html.erb
<h1>Editing Alumno</h1>

<%= render 'form' %>

<%= link_to 'Show', @alumno %> |
<%= link_to 'Back', alumnos_path %>

app/views/alumnos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alumnos</h1>

<table>
  <thead>
    <tr>
      <th>Rut</th>
      <th>Nombre</th>
      <th>Salida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
      <tr>
        <td><%= alumno.rut %></td>
        <td><%= alumno.nombre %></td>
        <td><%= alumno.salida %></td>
        <td><%= link_to 'Show', alumno %></td>
        <td><%= link_to 'Edit', edit_alumno_path(alumno) %></td>
        <td><%= link_to 'Destroy', alumno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumno', new_alumno_path %>

app/views/alumnos/new.html.erb
<h1>New Alumno</h1>

<%= render 'form' %>

<%= link_to 'Back', alumnos_path %>

app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rut:</strong>
  <%= @alumno.rut %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @alumno.nombre %>
</p>

<p>
  <strong>Salida:</strong>
  <%= @alumno.salida %>
</p>

<%= link_to 'Edit', edit_alumno_path(@alumno) %> |
<%= link_to 'Back', alumnos_path %>