config/routes.rb
Rails.application.routes.draw do
  get 'sacas/:fecha/:persona_id', to: 'sacas#new', as: 'new_saca'
  root 'sacas#index'
  resources :sacas
  resources :personas
  resources :alumnos
  resources :salidas

end

app/models/salida.rb
class Salida < ActiveRecord::Base
	has_many :alumnos
end

app/controllers/salidas_controller.rb
class SalidasController < ApplicationController
  before_action :set_salida, only: [:show, :edit, :update, :destroy]

  # GET /salidas
  # GET /salidas.json
  def index
    @salidas = Salida.all
  end

  # GET /salidas/1
  # GET /salidas/1.json
  def show
  end

  # GET /salidas/new
  def new
    @salida = Salida.new
  end

  # GET /salidas/1/edit
  def edit
  end

  # POST /salidas
  # POST /salidas.json
  def create
    @salida = Salida.new(salida_params)

    respond_to do |format|
      if @salida.save
        format.html { redirect_to @salida, notice: 'Salida was successfully created.' }
        format.json { render :show, status: :created, location: @salida }
      else
        format.html { render :new }
        format.json { render json: @salida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salidas/1
  # PATCH/PUT /salidas/1.json
  def update
    respond_to do |format|
      if @salida.update(salida_params)
        format.html { redirect_to @salida, notice: 'Salida was successfully updated.' }
        format.json { render :show, status: :ok, location: @salida }
      else
        format.html { render :edit }
        format.json { render json: @salida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salidas/1
  # DELETE /salidas/1.json
  def destroy
    @salida.destroy
    respond_to do |format|
      format.html { redirect_to salidas_url, notice: 'Salida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salida
      @salida = Salida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salida_params
      params.require(:salida).permit(:fecha)
    end
end

app/helpers/salidas_helper.rb
module SalidasHelper
end

app/views/salidas/_form.html.erb
<%= form_for(@salida) do |f| %>
  <% if @salida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salida.errors.count, "error") %> prohibited this salida from being saved:</h2>

      <ul>
      <% @salida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.datetime_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salidas/edit.html.erb
<h1>Editing Salida</h1>

<%= render 'form' %>

<%= link_to 'Show', @salida %> |
<%= link_to 'Back', salidas_path %>

app/views/salidas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Salidas</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salidas.each do |salida| %>
      <tr>
        <td><%= salida.fecha %></td>
        <td><%= link_to 'Show', salida %></td>
        <td><%= link_to 'Edit', edit_salida_path(salida) %></td>
        <td><%= link_to 'Destroy', salida, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salida', new_salida_path %>

app/views/salidas/new.html.erb
<h1>New Salida</h1>

<%= render 'form' %>

<%= link_to 'Back', salidas_path %>

app/views/salidas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @salida.fecha %>
</p>

<%= link_to 'Edit', edit_salida_path(@salida) %> |
<%= link_to 'Back', salidas_path %>