config/routes.rb
Rails.application.routes.draw do
  get 'sacas/:fecha/:persona_id', to: 'sacas#new', as: 'new_saca'
  root 'sacas#index'
  resources :sacas
  resources :personas
  resources :alumnos
  resources :salidas

end

app/models/saca.rb
class Saca < ActiveRecord::Base
  belongs_to :persona
end

app/controllers/sacas_controller.rb
class SacasController < ApplicationController
  before_action :set_saca, only: [:show, :edit, :update, :destroy]

  # GET /sacas
  # GET /sacas.json
  def index
    if params[:search]
      if Persona.exists?(rut: params[:search])
        @persona_id = Persona.find_by(rut: params[:search]).id        
        if @persona_id.present?
          @mes = Time.now.month
          @c = Saca.where("persona_id = ?", @persona_id).where("created_at >= ?", Date.today.at_beginning_of_month).count
          @sacas = Saca.where("persona_id = ?", @persona_id)
          redirect_to new_saca_path(@saca, fecha: Time.new, persona_id: @persona_id, c: @c)
        else 
          @sacas = Saca.where(persona_id: @persona_id).order("created_at DESC")
        end
      else
        @sacas = Saca.all.order("created_at DESC").limit(1)
      end
    else
      @sacas = Saca.all.order("created_at DESC").limit(1)
    end
    
  end

  # GET /sacas/1
  # GET /sacas/1.json
  def show
  end

  # GET /sacas/new
  def new
    @fecha = params[:fecha]
    @persona_id = params[:persona_id]
    @c = params[:c]
    @sacas = Saca.where("persona_id = ?", @persona_id)
    @saca = Saca.new(fecha: @fecha, persona_id: @persona_id)
  end

  # GET /sacas/1/edit
  def edit
  end

  # POST /sacas
  # POST /sacas.json
  def create
    @saca = Saca.new(saca_params)
    respond_to do |format|
      if @saca.save
        format.html { redirect_to action: "index", notice: 'Saca was successfully created.' }
        format.json { render :index, status: :created}
      else
        format.html { render :new }
        format.json { render json: @saca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sacas/1
  # PATCH/PUT /sacas/1.json
  def update
    respond_to do |format|
      if @saca.update(saca_params)
        format.html { redirect_to @saca, notice: 'Saca was successfully updated.' }
        format.json { render :show, status: :ok, location: @saca }
      else
        format.html { render :edit }
        format.json { render json: @saca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sacas/1
  # DELETE /sacas/1.json
  def destroy
    @saca.destroy
    respond_to do |format|
      format.html { redirect_to sacas_url, notice: 'Saca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saca
      @saca = Saca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saca_params
      params.require(:saca).permit(:fecha, :persona_id)
    end
end

app/helpers/sacas_helper.rb
module SacasHelper
end

app/views/sacas/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= form_for(@saca) do |f| %>
        <% if @saca.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@saca.errors.count, "error") %> prohibited this saca from being saved:</h2>

            <ul>
            <% @saca.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="fecha">
          <%= f.datetime_select :fecha %>
        </div>
        <div class="field">
          <%= f.hidden_field :persona_id, :value => @persona_id%>
        </div>
        <div class="col-md-12">
          <%= f.submit "Agregar Almuerzo", class: 'btn btn-primary btn-lg' %>
          <%= link_to 'Cancelar', sacas_path, class: 'btn btn-warning btn-lg' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sacas/_muestra_persona.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="presentacion">
			<h2>Rut: <%= @saca.persona.rut %></h2>
			<h2>Nombre: <%= @saca.persona.nombre %></h2>
		</div>
	</div>
</div>
	

app/views/sacas/_salidas.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="formulario-inicio">
			<%= form_tag(sacas_path, :method => "get", id: "search-form") do %>
			  <%= text_field_tag :search, params[:search], :autofocus => true, placeholder: "Ingresar Rut", class: 'form-control' %>
			  <%= submit_tag "Buscar Alumno", :name => nil, class: 'btn-formulario btn btn-success' %>
			<% end %>
		</div>
	</div>
</div>

app/views/sacas/edit.html.erb
<h1>Editing Saca</h1>

<%= render 'form' %>

<%= link_to 'Show', @saca %> |
<%= link_to 'Back', sacas_path %>

app/views/sacas/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= render "salidas" %>      
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>

      <h1>Registro Retiro Almuerzos</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Fecha</th>
            <th>Rut Alumno</th>
            <th>Persona</th>
          </tr>
        </thead>

        <tbody>
            <% @sacas.each do |saca| %>
              <tr>
                <td><%= saca.fecha %></td>
                <td><%= saca.persona.rut %></td>
                <td><%= saca.persona.nombre %></td>
              </tr>
            <% end %>
          
        </tbody>
      </table>

      <br>      
    </div>
  </div>
</div>

app/views/sacas/new.html.erb
<div class="container">
	<div class="row">
		<div class="formulario">
			<div class="col-md-12">
				<% if @saca.persona.cantidad.to_i > @c.to_i %>
					<%= render 'muestra_persona' %>
					<h2>Tiene: <%= @saca.persona.cantidad %> Almuerzo(s)</h2>
					<h2>Le quedan: <%= @saca.persona.cantidad.to_i - @c.to_i %> Almuerzos</h2>
					<%= render 'form' %>
				<% else %>
					<div class="error">
						<h1>Error: El alumno ya cumplió con sus <%= @c.to_i %> almuerzos.</h1>
						<%= link_to '<- Volver atrás', sacas_path, class: 'btn btn-warning btn-lg' %>
					</div>				
				<% end %>
			</div>
		</div>
	</div>

	<div class="tabla">
		<div class="row">
			<div class="col-md-12">
				<table class="table">
			        <thead>
			          <tr>
			            <th>Fecha</th>
			            <th>Rut Alumno</th>
			            <th>Nombre Alumno</th>
			          </tr>
			        </thead>

			        <tbody>
			            <% @sacas.each do |saca| %>
			              <tr>
			                <td><%= saca.fecha %></td>
			                <td><%= saca.persona.rut %></td>
			                <td><%= saca.persona.nombre %></td>
			              </tr>
			            <% end %>			          
			        </tbody>
			      </table>
			</div>
		</div>
	</div>
</div>

app/views/sacas/show.html.erb
<%= render 'form' %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @saca.fecha %>
</p>

<p>
  <strong>Persona:</strong>
  <%= @saca.persona.rut %>
</p>

<p>
  <strong>Nommbre:</strong>
  <%= @saca.persona.nombre %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @saca.persona.cantidad %>
</p>


<%= link_to 'Edit', edit_saca_path(@saca) %> |
<%= link_to 'Back', sacas_path %>