config/routes.rb
Rails.application.routes.draw do
  get 'sacas/:fecha/:persona_id', to: 'sacas#new', as: 'new_saca'
  root 'sacas#index'
  resources :sacas
  resources :personas
  resources :alumnos
  resources :salidas

end

app/models/persona.rb
class Persona < ActiveRecord::Base
	has_many :sacas
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:rut, :nombre, :cantidad)
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<div class="container">
  <%= form_for(@persona) do |f| %>
    <% if @persona.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

        <ul>
        <% @persona.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :rut %>
      <%= f.text_field :rut, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :rut %><br>
      <%= f.text_field :rut, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :nombre %><br>
      <%= f.text_field :nombre, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :cantidad %><br>
      <%= f.text_field :cantidad, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit "Editar Alumno", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/personas/edit.html.erb
<div class="container">
  <h1>Editing Persona</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @persona %> |
  <%= link_to 'Back', personas_path %>
</div>

app/views/personas/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>

      <h1>Registro Alumnos</h1>

      <%= link_to 'Nuevo Alumno', new_persona_path, class: 'btn btn-primary btn-lg' %>

      <table class="table">
        <thead>
          <tr>
            <th>Rut</th>
            <th>Nombre Completo</th>
            <th>Cantidad Almuerzos</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
            <% @personas.each do |persona| %>
              <tr>
                <td><%= persona.rut %></td>
                <td><%= persona.nombre %></td>
                <td><%= persona.cantidad %></td>
                <td><%= link_to 'Show', persona %></td>
                <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
                <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>

        </tbody>
      </table>

      <br>
    </div>
  </div>
</div>

app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <table class="table">
    <thead>
      <tr>
        <th><h4>Rut</h4></th>
        <th><h4>Nombre Completo</h4></th>
        <th><h4>Cantidad Almuerzos</h4></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><h4><%= @persona.rut %></h4></td>
        <td><h4><%= @persona.nombre %></h4></td>
        <td><h4><%= @persona.cantidad %></h4></td>
        <td><%= link_to 'Edit', edit_persona_path(@persona), class: 'btn btn-success btn-color-white' %></td>
      </tr>
    </tbody>
  </table>

  <table class="table">
    <thead>
      <tr>
        <th>Fecha Retiro Almuerzo</th>
      </tr>
    </thead>

    <tbody>
      <% if @persona.sacas.present? %>
        <% @persona.sacas.each do |saca| %>
          <tr>
            <td><h5><%= saca.fecha %></h5></td>
          </tr>
        <% end %>
      <% else %>
      <tr>
        <td><h4>El alumno no registra almuerzos sacados a la fecha</h4></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Back', personas_path, class: 'btn btn-success btn-color-white' %>
</div>